### ISSUE TITLE
Empty links with erroneous titles in classification facets

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#141]
When I do a search for http://lobid.org/nwbib/search?location=&q=* and select the "Sachgebiet" or "Region" facet, the lists start with empty labels. Selecting one /e.g. http://lobid.org/nwbib/search?q=*&nwbibsubject=http%3A%2F%2Fpurl.org%2Flobid%2Fnwbib%23s246000) and clicking on the resulting [title](http://lobid.org/nwbib/HT018602524) I get an error.

**Comment by fsteeg** [comment]
I think the issue here are missing items in our classifications. The unlabelled IDs are not in the nwbib index (see http://quaoar2.hbz-nrw.de:9200/_plugin/head/). My guess is that this was always true, but until recently, these empty labels were filtered out in the facets, so we never noticed it.

As a first step, I've deployed a fix to staging to display the URIs in the facets and the details view if no label is found, see: http://test.lobid.org/nwbib/search?q=

**Comment by acka47** [comment]
+1 A solution for the missing notations in NWBib classifications will be worked on with https://github.com/lobid/vocabs/issues/30.

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search?q=
