### ISSUE TITLE
Paging of detail views from result list doesn't work as expected

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#149]
Reported by NWBib stakeholder on 2015-09-29 (mail by U. Pflughaupt):

> Wenn man in einem Zehnerpäckchen einer Trefferliste blättert, sieht man nicht mehr die Gesamttrefferzahl  oder das Zahlensegment, in dem man sich gerade befindet, sondern immer z.B. „1 von 10 …“ auch wenn man schon den 100. Titel anschaut. Das finde ich nicht ideal, wenn man sich natürlich damit behelfen kann, die Anzeige auf 100 Titel pro Seite umzustellen. Man muss nach einem Zehnerpäckchen auch immer erst wieder in die Gesamt-Trefferliste, um dann das nächste Zehnerpäckchen aufzurufen. Das ist doch ein bisschen umständlich. Übrigens: wenn ich mit den SWern Köln Karneval eine Liste mit 173 Treffern erzielt habe, hakt gleich im ersten Zehnerpäckchen das Weiterblättern bei dem Titel Alaaf : das Magazin … und im zweiten Zehnerpäckchen bei dem Titel Kölner Narrenspiegel. Beides sind Zeitschriften. Ob das ein Grund sein kann?

**Comment by fsteeg** [comment]
Fixed the 'hanging' issue, deployed to staging, see clicking through this result list:
http://test.lobid.org/nwbib/search?subject=karneval+k%C3%B6ln+&size=25

Won't implement crossing from first result list to the next, or separate lists for search and favorites (as mentioned in a mail), as this would significantly complicate a feature that already has a high cost, due to storing data in the session. As it is now it's still somewhat focussed: page through the last result list. The link back to the list was implemented explicitly for the use case of enlarging the list or jumping to the next list page, I don't think it's too much of a hassle.

**Comment by acka47** [comment]
I am not sure whether we should close this one. Moving it to backlog for now.

**Comment by fsteeg** [comment]
The hanging issue was fixed, we communicated the other points, I think we can close this.
