### ISSUE TITLE
Re-order facets

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#202]
Reported by NWBib stakeholder G.C. on 2015-12-07:

> 1.	Reihenfolge der Facetten:
> a.	Erscheinungsjahr
> b.	Regionen (auch bei den Sucheinstiegen bieten wir erst Region, dann Sachgebiete)
> c.	Titel mit Bezug zu Orten in ganz NRW (erst wenn diese Facette anklickt wird, sollte die Karte Ortsbezug auftauchen. Den wortidentischen Eintrag ganz oben in der rechten Spalte über den Facetten würde ich dann ganz streichen, da es m. A. überflüssig ist, mit diesem Klick  wieder auf die Startseite geführt zu werden.
> d.	Sachgebiete (umfassender als Schlagwörter)
> e.	Schlagwörter
> f.	Medientypen (für den Nutzer vermutlich wichtiger als Publikationsformen)
> g.	Publikationsformen
> h.	Bestand in Bibliotheken

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search

I've tweaked the facet order and moved the location label from the top into the location facet. I think this is what G.C. meant. I've also generalized the location facet status label for the other facets, to easily see which facets are set and to remove the filters.

I think this also solves #203 in a sensible way (compact, in the same place as it's set).

I did not hide the coverage map if no location is searched, because even without a set location, the map provides a visualization of results (e.g. http://test.lobid.org/nwbib/search?q=braunkohle). It would be a pity to lose that. Instead, I made the coverage map coloring more reserved to integrate better.

**Comment by acka47** [comment]
+1 for the re-ordering. I will discuss the new orientation features in #203.

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/nwbib/search
