### ISSUE TITLE
Evaluating the usefulness of subject chains in NWBib data

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#209]
As implementing "Themensuche" and clickable subject chains will take some effort and as I have the feeling that no user except of some librarians will use these features, I would like to have some evidence regarding the potential usefulness of these features. 

Regarding clickable subject chains, I would like to have an answer to the question:

How many subject chains exist where clicking would lead you only to the exact entry where you clicked the subject chain in the first place? 

For the start, I would like to have an answer to the following question:
- Which and how many concrete instances of `subjectChain` only exist in one resource?  (Example: http://lobid.org/nwbib/search?q=%22Maas-Rhein+%7C+Planungsregion+%7C+R%C3%B6mer+%7C+Siedlung%22) 
  1. for all subject chains
  2. For subject chains with more than two elements

**Comment by fsteeg** [comment]
I did a quick try using a facets request but that doesn't work because the subjectChain field is analyzed, so we don't get a meaningful facets response. The dump-based appraoch you mentioned earlier is probably a better approach here.

**Comment by acka47** [comment]
With the last email by H.F. I think this question gets interesting again. I would really like to have this data. Moving to "Ready.

**Comment by fsteeg** [comment]
As a quick note on what we currently have:

The facets request I mentioned in https://github.com/hbz/nwbib/issues/209#issuecomment-165749996 is possible by now via our `not_analyzed` raw field:

http://lobid.org/resource/facets?set=http://lobid.org/resource/NWBib&q=*&size=9999&from=0&field=@graph.http://purl.org/lobid/lv%23subjectChain.@value.raw

It does not answer your questions though, since

1) the result is cut off after our current max value (paging does not seem to have an effect here) and 
2) I can't seem to find a way to search for the `|` sign, which would only show chains with >=2 elements

It still provides insight into the `subjectChain` data.

**Comment by acka47** [comment]
Re. 1) we can get the whole data by using the scroll parameter, e.g. `curl -H "Accept: application/json" "http://lobid.org/resource/facets?set=http://lobid.org/resource/NWBib&q=*&size=9999&from=0&field=@graph.http://purl.org/lobid/lv%23subjectChain.@value.raw&scroll=*"`

**Comment by acka47** [comment]
> Re. 1) we can get the whole data by using the scroll parameter

Actually it doesn't work as expected...

**Comment by acka47** [comment]
Closing
