### ISSUE TITLE
Only show small version of "Raumbezug" map

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#236]
Requested by stakeholders as of mail from 2016-01-26 by G.C.:

>	Die Karte "Raumbezug" sollte unbedingt kleiner (thumbnail)
	dargestellt werden; der interessierte Nutzer kann dann mit einem Klick die
	Karte aufmachen.  Zwar stellt diese geographische Navigation einen
	alternativen Zugang dar, jedoch ist die Karte in ihrer jetzigen Größe
	ein eye-catcher und hebt sich dadurch sehr von den anderen
	Facetten ab. Sie erschließt sich nicht unbedingt intuitiv, ist eher schwerfällig,
	um auf die unterste Stufe zu gelangen und verdeckt auch die danach
	angeordneten wichtigen Facetten Sachgebiete/Schlagwörter, die erst
	durch scrollen zu sehen sind.

**Comment by fsteeg** [comment]
We should not hide the map by default, in particular because we'd lose the spatial visualization aspect, which is one of the defining characteristics of a regional bibliography and NWBib in particular.

I've significantly decreased the size of the map and moved it back up to the `issued` facet (which also provides a visualization), to avoid cutting off the textual facets as mentioned by stakeholders.

Deployed to staging, here are some examples that illustrate the visualization aspect:

http://test.lobid.org/nwbib/search?q=schiefer
http://test.lobid.org/nwbib/search?q=islam
http://test.lobid.org/nwbib/search?q=forstwirtschaft
http://test.lobid.org/nwbib/search?q=gedichte
http://test.lobid.org/nwbib/search?q=alternatives+wohnen
http://test.lobid.org/nwbib/search?q=heinrich+böll

We should also address the other issues brought up by stakeholders in a reply. Will send a draft by mail.

**Comment by acka47** [comment]
G.C. writes:
> Sie erschließt sich nicht unbedingt intuitiv, ist eher schwerfällig,
um auf die unterste Stufe zu gelangen

To make the map facet more intuitive, I suggest the following:

1. Enable scrolling only via mouse scrolling and Strg++
2. Don't open a popup when clicking on a cluster or pin but directly apply the facet to the result list.

**Comment by fsteeg** [comment]
Deployed to staging, see: http://test.lobid.org/nwbib/search?q=heinrich+böll

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
Deployed to production, closing. See: http://lobid.org/nwbib/search?q=heinrich+böll
