### ISSUE TITLE
Implement search functionality with API 2.0

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#262]
This would solve the following issues reported by I.N. on 2015-12-02:

> 1._Schlagwortrecherche_: Das Abschneiden derUnterfelder des Bevorzugen 
> Namens wirkt sich in Abhängigkeit davon aus, ob abweichende Namensformen 
> erfasst wurden oder nicht. Abweichende Namensformen werden im Lobid-Feld 
> „subjectLabel“ mit in die Recherche eingebunden, so dass abgeschnittene 
> Formen beim Bevorzugten Namen kompensiert werden können. So wird ein 
> Titel als Treffer gefunden, wenn das untergeordnete Element (= 
> abgeschnittenes Unterfeld des Bevorzugten Namens) als Verweisungsform im 
> GND-Feld 410 bzw. 451 eingetragen wurde.
> 
> Beispiel für korrekte Treffer, weil Verweisungsformen die abgeschnittene 
> Namensform kompensieren: Heinrich-Heine-Institut | b Rheinisches 
> Literaturarchiv
> 
> Beispiel für fehlende Treffer, weil Verweisungsformen fehlen: 
> LWL-Archivamt für Westfalen | b Westfälisches Literaturarchiv
> 
> 3._Körperschaftsrecherche_: Bei der Körperschaftsrecherche wird im 
> Lobid-Feld „contributingCorporateBodyLabel“ gesucht. Hier wirkt sich das 
> Fehlen der Unterfelder (im Beispiel des mittleren Elements) negativ aus. 
> Da die Elemente des Unterfeldes fehlen, wird kein Treffer gefunden.
> 
> Beispiel: KS-Recherche mit „Landschaftsversammlung Fraktion“ oder 
> „Landschaftsversammlung Bündnis“ oder „Landschaftsversammlung Grünen“ 
> ergibt keinen Treffer

**Comment by fsteeg** [comment]
If I'm not mistaken, this depends on https://github.com/hbz/lobid-rdf-to-json/issues/24 (correct, @acka47?)

**Comment by acka47** [comment]
> If I'm not mistaken, this depends on https://github.com/hbz/lobid-rdf-to-json/issues/24 (correct, @acka47?)

Yes, and another issue to created based on https://github.com/hbz/lobid-resources/issues/10 re. indicating contributor role via "role"+ MARC relator code instead of using the relator code as property...

**Comment by fsteeg** [comment]
Also depends on #83

**Comment by fsteeg** [comment]
As a heads-up, in particular for @acka47:

I don't think it's realistic or even advisable to implement this for nwbib-launch, which is in about 1 month:

1. It depends on another large issue: #83 (which is actually 'Implement geodata inclusion for data 2.0')
2. We have [a few smaller nwbib-launch issues](https://github.com/hbz/nwbib/issues?q=is%3Aissue+is%3Aopen+label%3Anwbib-launch) to be implemented before even starting work on #83
3. Switching search to data/API 2.0 is a considerably larger step than the details switch we performed about three weeks ago (https://github.com/hbz/nwbib/commit/df35c9f6e46df33d1dc92793c28101de35b7a4af), and we're still fixing bugs caused by that (last one today, https://github.com/hbz/nwbib/commit/2b6a0b0910608dbe351e9c938ecc00a1ca12fe8d). Given that experience, even if it was possible to actually implement this until the launch (which I don't think so, given it requires #83 and API that does not even exist), it would certainly cause severe issues in the newly launched nwbib

Instead, I think it makes sense to start working on this after the launch, at http://beta.nwbib.de. This is in line with [what we decided in our planning meeting](https://wiki1.hbz-nrw.de/display/SEM/Projektmanagement#Projektmanagement-Aktivit%C3%A4ten2016%C3%9Cberblick): 'Mai: NWBib-Anpassungen API 2.0 (Fabian)'

Removing nwbib-launch label for this and #83.

**Comment by fsteeg** [comment]
Depends on https://github.com/hbz/nwbib/issues/262

**Comment by fsteeg** [comment]
Issue https://github.com/hbz/nwbib/issues/163 contains more up-to-date info and context about this. Closing.
