### ISSUE TITLE
Wrong results with geo search for "Mülheim a. d. Ruhr"

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#86]
Reported by user (see [wiki](https://wiki1.hbz-nrw.de/pages/diffpagesbyversion.action?pageId=42401798&selectedPageVersions=101&selectedPageVersions=100)). Clicking on "[Mülheim a. d. Ruhr](http://lobid.org/nwbib/search?location=M%C3%BClheim%20an%20der%20Ruhr|51.5,6.9+51.5,6.9%2051.5,6.9%2051.4,6.9%2051.4,7.0%2051.4,7.0%2051.4,7.0%2051.4,7.0%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.8%2051.4,6.9%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.5,6.8%2051.5,6.8%2051.4,6.8%2051.5,6.8%2051.5,6.8%2051.5,6.9%2051.5,6.9%2051.5,6.9)" on the map gives results for "Oberhausen-Osterfeld" (Wikidata entity: http://www.wikidata.org/entity/Q2035183).

**Comment by acka47** [comment]
There are at least three problems:

1. Probably there is a problem with the [polygon](http://lobid.org/nwbib/search?location=M%C3%BClheim%20an%20der%20Ruhr|51.5,6.9+51.5,6.9%2051.5,6.9%2051.4,6.9%2051.4,7.0%2051.4,7.0%2051.4,7.0%2051.4,7.0%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.9%2051.4,6.8%2051.4,6.9%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.4,6.8%2051.5,6.8%2051.5,6.8%2051.4,6.8%2051.5,6.8%2051.5,6.8%2051.5,6.9%2051.5,6.9%2051.5,6.9) that is input for Mülheim a. d. Ruhr or with the geo coordinates in Wikidata.
2. Titles with `700n 	|a 99 |b Mülheim an der Ruhr` don't get a link to http://www.wikidata.org/entity/Q2899 during transformation, e.g. http://lobid.org/resource/HT018344163. (Entries  with `700n 	|a 99 |b Mülheim'' that also denote "Mülheim an der Ruhr" are transformed correctly, though, see e.g. http://lobid.org/resource/HT012844583.)

BTW, entries with `700n |a 99 |b Mühlheim <Ruhr>` are linked to http://www.wikidata.org/entity/Q327896 which is Köln-Mülheim. (That is due to the 'h' in ühlheim that was catalogued incorretly.)

**Comment by acka47** [comment]
The linking will be improved by #83 which should be solved first.

**Comment by acka47** [comment]
> or with the geo coordinates in Wikidata.

Wrong geo coordinates in wikidata are NOT the problem. These are `51°30'N, 6°54'E` for Oberhausen-Osterfeld which looks correct (see https://goo.gl/maps/Pi1wh).

**Comment by fsteeg** [comment]
This might be an issue with the precision of the polygon that we use. We use coordinates with one decimal digit to avoid too large URLs, see:

https://github.com/hbz/nwbib/blob/master/app/views/tags/nrw_map.scala.html#L47

At our latitude, this results in a precision of about 6 km, see:

http://en.wikipedia.org/wiki/Decimal_degrees

The different polygons on our map differ in their number of coordinates. Increasing the decimal digits to 2 might work for some polygons. It also might work with the internal Play server (Netty), but cause issues with our Apache proxy, since different servers implement different limits. Finally, browsers can be an issue too.

The best solution would probably be to use some sort of alias as the parameter, which we map to the actual, detailed polygon internally. So we'd just call `location=Kreis+Coesfeld` and handle the coordinates internally. If I remember correctly this is what @jschnasse suggested when I discussed this with him.

**Comment by fsteeg** [comment]
Seems like my hunch from https://github.com/hbz/nwbib/issues/86#issuecomment-72362916 was correct: with higher precision the Mülheim query yields less results, and none with Osterfeld: [Mülheim an der Ruhr](http://test.lobid.org/nwbib/search?location=M%C3%BClheim%20an%20der%20Ruhr|51.46,6.92+51.45,6.92%2051.45,6.92%2051.45,6.95%2051.44,6.96%2051.43,6.96%2051.43,6.95%2051.42,6.95%2051.42,6.94%2051.40,6.94%2051.40,6.94%2051.39,6.94%2051.39,6.94%2051.38,6.93%2051.38,6.91%2051.38,6.91%2051.37,6.92%2051.37,6.91%2051.37,6.90%2051.37,6.89%2051.36,6.88%2051.36,6.87%2051.36,6.87%2051.36,6.86%2051.36,6.85%2051.36,6.85%2051.35,6.83%2051.37,6.82%2051.37,6.82%2051.38,6.81%2051.40,6.82%2051.40,6.81%2051.41,6.82%2051.44,6.82%2051.44,6.82%2051.45,6.81%2051.46,6.81%2051.46,6.82%2051.45,6.83%2051.45,6.84%2051.46,6.85%2051.46,6.87%2051.47,6.90%2051.46,6.92) (query against staging).

As the higher precision results in too long URLs for some (large, contorted) polygons, the higher precision is not used for these. Since these are larger districts, the lower precision might work just fine. If not, we will have to implement a solution as mentioned in https://github.com/hbz/nwbib/issues/86#issuecomment-72362916.

**Comment by acka47** [comment]
As said in https://github.com/hbz/nwbib/issues/86#issuecomment-71474011, I think @dr0i should first improve the wikidata mapping.

**Comment by fsteeg** [comment]
Ah, I thought what you said in https://github.com/hbz/nwbib/issues/86#issuecomment-71474622 meant that this was not the problem. But regardless of other issues, I think the higher precision fixes the issue now and makes a lot of sense, since about 6 km is not precise enough for the smaller districts.

**Comment by acka47** [comment]
> But regardless of other issues, I think the higher precision fixes the issue now and makes a lot of sense, since about 6 km is not precise enough for the smaller districts.

You are right. +1 from me.
