### ISSUE TITLE
Title query over union of title and adtionalTitle fields

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#87]
Reported by customer, see https://wiki1.hbz-nrw.de/pages/diffpagesbyversion.action?pageId=42401798&selectedPageVersions=97&selectedPageVersions=96.

Example: The query http://lobid.org/nwbib/search?name=Bildungswege+Weckruf currently doesn't deliver http://lobid.org/nwbib/HT018504288 which has title "Marl: Bildungswege zu einer neuen Stadt "  and additional title "ein programmatischer Weckruf ".

**Comment by fsteeg** [comment]
The corresponding query is currently configured to match the query tokens with AND, see:

https://github.com/hbz/lobid/blob/master/app/models/queries/LobidResources.java#L86

In the example `Bildungswege` and `Weckruf` appear in different fields. That might be causing this issue. I think having the AND query is due to the requested AND-by-default behaviour. Simply switching to OR here might yield undesired results, where only one token actually matches (against *any* field). But there is probably some Elasticsearch option that implements what we want here.

**Comment by dr0i** [comment]
@fsteeg u're right, there is an ES option :)

**Comment by dr0i** [comment]
Deployed to staging, see http://test.lobid.org/resource?name=Bildungswege%20Weckruf .

**Comment by dr0i** [comment]
Re-deployed to staging small test set, please try http://test.lobid.org/resource?name=ossia%20elise.

**Comment by acka47** [comment]
In the new example the query matches information in fields `title` and `alternativeTitle` while the original example was about the fields `title` and `otherTitleInformation`.

Obviously, the original use case is also covered, see http://test.lobid.org/resource?name=dankrede%20gr%C3%A4finn. 

Thus: +1

**Comment by dr0i** [comment]
Deployed to production, closing.
