### ISSUE TITLE
Filter by publication date

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#96]
As a user I want to filter results by publication date choosing a specific year or a range of years.

**Comment by fsteeg** [comment]
Deployed simple implementation to staging: http://test.lobid.org/nwbib/search?q=ehrenfeld

No slider, no histogram (yet).

@acka47 should we deploy this as a first step or would you prefer to wait until we have a slider?

**Comment by acka47** [comment]
I prefer to wait for the slider, histogram is a nice bonus, though.

**Comment by fsteeg** [comment]
Deployed slider and bar chart to staging, see: http://test.lobid.org/nwbib/search?q=nrw

**Comment by acka47** [comment]
Looks good and also works good in Firefox. The slider doesn't work in chromium, though.

Also, I think it might make sense to show the number of results in brackets behind the year range when people are moving the slider. So they know how many results to expect with a specific filter. Is this possible?

**Comment by fsteeg** [comment]
Deployed fix for the Chromium issue and preview of expected hits while sliding to staging.

To avoid HTTP requests while sliding, I've implemented the hits preview by summing the facets count for the time range. Since some resources have ranges in their `issued` field however, this is not always accurate (for an example, see requests `1` and `2`, which yield 4 and 5 results, giving 9 as the estimated result for the range, but since both contain HT007000722, the actual range request `3` yields only 8 results), so I display `ca. X Treffer` in the preview.

`1` http://lobid.org/resource?set=nwbib&q=ehrenfeld&issued=1985&format=full
`2` http://lobid.org/resource?set=nwbib&q=ehrenfeld&issued=1986&format=full
`3` http://lobid.org/resource?set=nwbib&q=ehrenfeld&issued=1985-1986&format=full

**Comment by acka47** [comment]
I like it very much now. +1

**Comment by fsteeg** [comment]
Deployed to production, closing. See http://lobid.org/nwbib/search?q=nrw
